---
services:
  influxdb:
    container_name: influxdb
    image: docker.io/influxdb:2.7.6
    ports:
      - 8086:8086
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    restart: unless-stopped

  sbflite2:
    container_name: SBFlite2
    build: ./Solar/SBFlite2/
    restart: unless-stopped
    volumes:
      - ./config.toml:/etc/sbflite/config.toml 
